import { prisma } from "../config/database";
import { logger } from "../config/logger";

interface AuditEntry {
  userId?: string | null;
  action: string;
  entity: string;
  entityId?: string | null;
  metadata?: Record<string, unknown>;
  ipAddress?: string | null;
}

/**
 * Fire-and-forget audit trail writer for Auth & RBAC events (login,
 * logout, password changes, staff account lifecycle, role/permission
 * changes). Never throws into the caller's request flow — an audit
 * write failure should be logged, not turned into a 500 for the user.
 */
export async function recordAudit(entry: AuditEntry): Promise<void> {
  try {
    await prisma.auditLog.create({
      data: {
        userId: entry.userId ?? null,
        action: entry.action,
        entity: entry.entity,
        entityId: entry.entityId ?? null,
        metadata: entry.metadata as any,
        ipAddress: entry.ipAddress ?? null,
      },
    });
  } catch (err) {
    logger.error("Failed to write audit log", { entry, err });
  }
}

export const AuditActions = {
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  LOGIN_LOCKED: "AUTH_LOGIN_LOCKED_OUT",
  LOGOUT: "AUTH_LOGOUT",
  LOGOUT_ALL: "AUTH_LOGOUT_ALL_SESSIONS",
  REGISTER: "AUTH_REGISTER",
  TOKEN_REFRESH: "AUTH_TOKEN_REFRESH",
  TOKEN_REUSE_DETECTED: "AUTH_REFRESH_TOKEN_REUSE_DETECTED",
  FORGOT_PASSWORD_REQUESTED: "AUTH_FORGOT_PASSWORD_REQUESTED",
  PASSWORD_RESET: "AUTH_PASSWORD_RESET",
  SESSION_REVOKED: "AUTH_SESSION_REVOKED",
  STAFF_CREATED: "RBAC_STAFF_CREATED",
  STAFF_UPDATED: "RBAC_STAFF_UPDATED",
  STAFF_ROLE_CHANGED: "RBAC_STAFF_ROLE_CHANGED",
  STAFF_PASSWORD_RESET: "RBAC_STAFF_PASSWORD_RESET_BY_ADMIN",
  STAFF_DEACTIVATED: "RBAC_STAFF_DEACTIVATED",
  STAFF_RESTORED: "RBAC_STAFF_RESTORED",

  // Property Management module
  HOTEL_CREATED: "PROPERTY_HOTEL_CREATED",
  HOTEL_UPDATED: "PROPERTY_HOTEL_UPDATED",
  HOTEL_DEACTIVATED: "PROPERTY_HOTEL_DEACTIVATED",
  HOTEL_RESTORED: "PROPERTY_HOTEL_RESTORED",
  HOTEL_DELETED_PERMANENT: "PROPERTY_HOTEL_DELETED_PERMANENT",
  HOTEL_TYPE_CREATED: "PROPERTY_HOTEL_TYPE_CREATED",
  HOTEL_TYPE_UPDATED: "PROPERTY_HOTEL_TYPE_UPDATED",
  HOTEL_TYPE_REMOVED: "PROPERTY_HOTEL_TYPE_REMOVED",
  WEBSITE_LISTING_UPDATED: "PROPERTY_WEBSITE_LISTING_UPDATED",
  ROOM_CATEGORY_CREATED: "PROPERTY_ROOM_CATEGORY_CREATED",
  ROOM_CATEGORY_UPDATED: "PROPERTY_ROOM_CATEGORY_UPDATED",
  ROOM_CATEGORY_REMOVED: "PROPERTY_ROOM_CATEGORY_REMOVED",
  ROOM_TYPE_CREATED: "PROPERTY_ROOM_TYPE_CREATED",
  ROOM_TYPE_UPDATED: "PROPERTY_ROOM_TYPE_UPDATED",
  ROOM_TYPE_DELETED: "PROPERTY_ROOM_TYPE_DELETED",
  ROOM_CREATED: "PROPERTY_ROOM_CREATED",
  ROOM_UPDATED: "PROPERTY_ROOM_UPDATED",
  ROOM_DELETED: "PROPERTY_ROOM_DELETED",
  ROOM_STATUS_CHANGED: "PROPERTY_ROOM_STATUS_CHANGED",
  ROOMS_BULK_CREATED: "PROPERTY_ROOMS_BULK_CREATED",

  // Reservation Management module
  BOOKING_CREATED: "RESERVATION_BOOKING_CREATED",
  BOOKING_AMENDED: "RESERVATION_BOOKING_AMENDED",
  BOOKING_STATUS_CHANGED: "RESERVATION_BOOKING_STATUS_CHANGED",
  BOOKING_CHECKED_IN: "RESERVATION_BOOKING_CHECKED_IN",
  BOOKING_CHECKED_OUT: "RESERVATION_BOOKING_CHECKED_OUT",
  BOOKING_CANCELLED: "RESERVATION_BOOKING_CANCELLED",
  BOOKING_NO_SHOW: "RESERVATION_BOOKING_NO_SHOW",
  BOOKING_NO_SHOW_AUTO: "RESERVATION_BOOKING_NO_SHOW_AUTO",
  BOOKING_DELETED: "RESERVATION_BOOKING_DELETED",
  PAYMENT_RECORDED: "PAYMENT_RECORDED",
  PAYMENT_WEBHOOK_DUPLICATE_IGNORED: "PAYMENT_WEBHOOK_DUPLICATE_IGNORED",
  GUEST_CREATED: "GUEST_CREATED",
  GUEST_UPDATED: "GUEST_UPDATED",
  GUEST_DELETED: "GUEST_DELETED",
  HOUSEKEEPING_TASK_CREATED: "HOUSEKEEPING_TASK_CREATED",
  HOUSEKEEPING_TASK_UPDATED: "HOUSEKEEPING_TASK_UPDATED",
  HOUSEKEEPING_TASK_DELETED: "HOUSEKEEPING_TASK_DELETED",
  MAINTENANCE_REQUEST_CREATED: "MAINTENANCE_REQUEST_CREATED",
  MAINTENANCE_REQUEST_UPDATED: "MAINTENANCE_REQUEST_UPDATED",
  MAINTENANCE_REQUEST_DELETED: "MAINTENANCE_REQUEST_DELETED",
  ASSET_CREATED: "ASSET_CREATED",
  ASSET_UPDATED: "ASSET_UPDATED",
  ASSET_DELETED: "ASSET_DELETED",
  REVIEW_RESPONDED: "REVIEW_RESPONDED",

  // Financial Management module
  FINANCE_INVOICE_CREATED: "FINANCE_INVOICE_CREATED",
  FINANCE_INVOICE_UPDATED: "FINANCE_INVOICE_UPDATED",
  FINANCE_INVOICE_ISSUED: "FINANCE_INVOICE_ISSUED",
  FINANCE_INVOICE_VOIDED: "FINANCE_INVOICE_VOIDED",
  FINANCE_INVOICE_PAID: "FINANCE_INVOICE_PAID",
  FINANCE_CREDIT_NOTE_ISSUED: "FINANCE_CREDIT_NOTE_ISSUED",
  FINANCE_CREDIT_NOTE_VOIDED: "FINANCE_CREDIT_NOTE_VOIDED",
  FINANCE_REFUND_REQUESTED: "FINANCE_REFUND_REQUESTED",
  FINANCE_REFUND_APPROVED: "FINANCE_REFUND_APPROVED",
  FINANCE_REFUND_REJECTED: "FINANCE_REFUND_REJECTED",
  FINANCE_REFUND_PROCESSED: "FINANCE_REFUND_PROCESSED",
  FINANCE_TAX_RATE_CREATED: "FINANCE_TAX_RATE_CREATED",
  FINANCE_TAX_RATE_UPDATED: "FINANCE_TAX_RATE_UPDATED",
  FINANCE_TAX_RATE_DEACTIVATED: "FINANCE_TAX_RATE_DEACTIVATED",
  FINANCE_LEDGER_MANUAL_ENTRY: "FINANCE_LEDGER_MANUAL_ENTRY",
  FINANCE_PERIOD_CLOSED: "FINANCE_PERIOD_CLOSED",
  FINANCE_PERIOD_REOPENED: "FINANCE_PERIOD_REOPENED",

  // Expense Management module
  EXPENSE_CREATED: "EXPENSE_CREATED",
  EXPENSE_UPDATED: "EXPENSE_UPDATED",
  EXPENSE_DELETED: "EXPENSE_DELETED",
  EXPENSE_APPROVED: "EXPENSE_APPROVED",
  EXPENSE_REJECTED: "EXPENSE_REJECTED",
  EXPENSE_REIMBURSED: "EXPENSE_REIMBURSED",
  EXPENSE_PAID: "EXPENSE_PAID",
  EXPENSE_CATEGORY_CREATED: "EXPENSE_CATEGORY_CREATED",
  EXPENSE_CATEGORY_UPDATED: "EXPENSE_CATEGORY_UPDATED",
  VENDOR_CREATED: "VENDOR_CREATED",
  VENDOR_UPDATED: "VENDOR_UPDATED",
  VENDOR_DEACTIVATED: "VENDOR_DEACTIVATED",
  EXPENSE_BUDGET_CREATED: "EXPENSE_BUDGET_CREATED",
  EXPENSE_BUDGET_UPDATED: "EXPENSE_BUDGET_UPDATED",
  EXPENSE_BUDGET_DELETED: "EXPENSE_BUDGET_DELETED",
  RECURRING_EXPENSE_CREATED: "RECURRING_EXPENSE_CREATED",
  RECURRING_EXPENSE_UPDATED: "RECURRING_EXPENSE_UPDATED",
  RECURRING_EXPENSE_PAUSED: "RECURRING_EXPENSE_PAUSED",
  RECURRING_EXPENSE_RESUMED: "RECURRING_EXPENSE_RESUMED",
  RECURRING_EXPENSE_DELETED: "RECURRING_EXPENSE_DELETED",
  RECURRING_EXPENSE_GENERATED: "RECURRING_EXPENSE_GENERATED",
} as const;
