import { prisma } from "../../../config/database";
import { ApiError } from "../../../utils/ApiError";

const includeGraph = { category: true, vendor: true };

function advance(date: Date, frequency: string): Date {
  const next = new Date(date);
  switch (frequency) {
    case "WEEKLY":
      next.setUTCDate(next.getUTCDate() + 7);
      break;
    case "MONTHLY":
      next.setUTCMonth(next.getUTCMonth() + 1);
      break;
    case "QUARTERLY":
      next.setUTCMonth(next.getUTCMonth() + 3);
      break;
    case "YEARLY":
      next.setUTCFullYear(next.getUTCFullYear() + 1);
      break;
  }
  return next;
}

export const recurringExpenseService = {
  async list(hotelId: string, includeInactive = false) {
    return prisma.recurringExpense.findMany({
      where: { hotelId, ...(includeInactive ? {} : { isActive: true }) },
      include: includeGraph,
      orderBy: { nextRunDate: "asc" },
    });
  },

  async get(hotelId: string, id: string) {
    const item = await prisma.recurringExpense.findFirst({ where: { id, hotelId }, include: includeGraph });
    if (!item) throw ApiError.notFound("Recurring expense not found");
    return item;
  },

  async create(hotelId: string, createdById: string | undefined, data: any) {
    if (data.categoryId) {
      const category = await prisma.expenseCategory.findFirst({ where: { id: data.categoryId, OR: [{ hotelId }, { hotelId: null }] } });
      if (!category) throw ApiError.badRequest("Expense category not found");
    }
    if (data.vendorId) {
      const vendor = await prisma.vendor.findFirst({ where: { id: data.vendorId, OR: [{ hotelId }, { hotelId: null }] } });
      if (!vendor) throw ApiError.badRequest("Vendor not found");
    }
    const startDate = new Date(data.startDate);
    return prisma.recurringExpense.create({
      data: {
        hotelId,
        title: data.title,
        description: data.description,
        amount: data.amount,
        categoryId: data.categoryId,
        vendorId: data.vendorId,
        isReimbursable: data.isReimbursable ?? false,
        frequency: data.frequency,
        startDate,
        endDate: data.endDate ? new Date(data.endDate) : undefined,
        nextRunDate: startDate,
        createdById,
      },
      include: includeGraph,
    });
  },

  async update(hotelId: string, id: string, data: any) {
    const existing = await prisma.recurringExpense.findFirst({ where: { id, hotelId } });
    if (!existing) throw ApiError.notFound("Recurring expense not found");
    return prisma.recurringExpense.update({
      where: { id },
      data: { ...data, endDate: data.endDate === undefined ? undefined : data.endDate ? new Date(data.endDate) : null },
      include: includeGraph,
    });
  },

  async setActive(hotelId: string, id: string, isActive: boolean) {
    const existing = await prisma.recurringExpense.findFirst({ where: { id, hotelId } });
    if (!existing) throw ApiError.notFound("Recurring expense not found");
    return prisma.recurringExpense.update({ where: { id }, data: { isActive }, include: includeGraph });
  },

  async remove(hotelId: string, id: string) {
    const existing = await prisma.recurringExpense.findFirst({ where: { id, hotelId } });
    if (!existing) throw ApiError.notFound("Recurring expense not found");
    // Generated Expense rows keep their history — the FK is ON DELETE SET NULL.
    await prisma.recurringExpense.delete({ where: { id } });
    return { id };
  },

  /**
   * Scans every active template whose `nextRunDate` has arrived, creates a
   * real SUBMITTED Expense for each, and advances `nextRunDate` by its
   * frequency (auto-deactivating once past `endDate`). Called by the daily
   * BullMQ sweep; safe to call more than once close together since each
   * due template only produces one Expense per invocation and its
   * `nextRunDate` moves forward immediately within the same transaction.
   */
  async runDueRecurringExpenses(now: Date = new Date()) {
    const due = await prisma.recurringExpense.findMany({
      where: { isActive: true, nextRunDate: { lte: now } },
    });

    const generated: any[] = [];
    for (const template of due) {
      const expense = await prisma.$transaction(async (tx: any) => {
        const created = await tx.expense.create({
          data: {
            hotelId: template.hotelId,
            categoryId: template.categoryId,
            vendorId: template.vendorId,
            title: template.title,
            description: template.description ?? `Auto-generated by recurring expense "${template.title}"`,
            amount: template.amount,
            isReimbursable: template.isReimbursable,
            status: "SUBMITTED",
            expenseDate: template.nextRunDate,
            submittedById: template.createdById,
            recurringExpenseId: template.id,
          },
          include: { category: true, vendorRecord: true },
        });

        const nextRunDate = advance(template.nextRunDate, template.frequency);
        const pastEnd = template.endDate ? nextRunDate > template.endDate : false;
        await tx.recurringExpense.update({
          where: { id: template.id },
          data: { nextRunDate, lastRunAt: now, isActive: pastEnd ? false : template.isActive },
        });

        return created;
      });
      generated.push(expense);
    }
    return generated;
  },
};
